version: "3"
services:
  bookshelf:
    stdin_open: true
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    environment:
      - CLIENT_ID=$CLIENT_ID
      - CLIENT_SECRET=$CLIENT_SECRET
      - REDIRECT_URL=$REDIRECT_URL
      - SECURITY_KEY=$SECURITY_KEY
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - WEBHOOK_URL=$WEBHOOK_URL
      - CHANNEL=$CHANNEL
      - REDIS_ADDR=$REDIS_ADDR
      - REDIS_PASS=$REDIS_PASS
    ports:
    - "8080:8080"
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    ports:
    - "6379:6379"
    environment:
      - TZ=Asia/Tokyo
    volumes:
    - "./data/redis:/data"