basePath: /v1
definitions:
  entity.Book:
    properties:
      author:
        type: string
      createDate:
        type: string
      createUserID:
        type: integer
      dateOfIssue:
        type: string
      deleteDate:
        type: string
      deleteFlag:
        type: integer
      deleteUserID:
        type: integer
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      publisher:
        type: string
      updateDate:
        type: string
      updateUserID:
        type: integer
    type: object
info:
  contact: {}
  description: 読書●ーターを参考にした下位互換API
  title: bookshelf-api
  version: 0.0.0
paths:
  /book:
    post:
      consumes:
      - application/json
      description: 本の更新
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Book'
  /book/{id}:
    delete:
      consumes:
      - application/json
      description: 本の削除
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/entity.Book'
    get:
      consumes:
      - application/json
      description: idによる本の取得
      parameters:
      - description: 本のID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Book'
  /version:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: バージョン情報を文字列で返す
swagger: "2.0"
